import uuid
from sqlalchemy import Boolean, CheckConstraint, Column, DateTime, ForeignKey, Index, Integer, String, Text, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from app.models.models import Base

def _id(): return Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

class AgentRun(Base):
    __tablename__ = "agent_runs"
    __table_args__ = (Index("uq_agent_runs_live", "agent_id", "trigger_event_id", unique=True, postgresql_where=text("mode = 'live'")), Index("idx_agent_runs_agent_status", "agent_id", "status"), Index("idx_agent_runs_thread_route", "thread_id", "route", "queued_at"), Index("idx_agent_runs_parent_root", "parent_run_id", "root_run_id", "depth"), CheckConstraint("mode IN ('live','dry_run','replay','canary_shadow')"), CheckConstraint("depth >= 0"), CheckConstraint("status IN ('queued','running','waiting_approval','waiting_handoff','succeeded','exhausted','timed_out','cancelled','failed','suppressed','dead_lettered','outcome_unknown')"))
    id=_id(); workspace_id=Column(UUID(as_uuid=True),ForeignKey("workspaces.id",ondelete="CASCADE"),nullable=False); agent_id=Column(UUID(as_uuid=True),ForeignKey("agents.id",ondelete="RESTRICT"),nullable=False); agent_version_id=Column(UUID(as_uuid=True),ForeignKey("agent_versions.id",ondelete="RESTRICT"),nullable=False); thread_id=Column(UUID(as_uuid=True),ForeignKey("threads.id",ondelete="RESTRICT"),nullable=False); trigger_event_id=Column(UUID(as_uuid=True),ForeignKey("trigger_events.id",ondelete="SET NULL")); source_run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="SET NULL")); source_trigger_event_id=Column(UUID(as_uuid=True),ForeignKey("trigger_events.id",ondelete="SET NULL")); input_message_id=Column(UUID(as_uuid=True),ForeignKey("messages.id",ondelete="SET NULL")); parent_run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="SET NULL")); root_run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="SET NULL")); depth=Column(Integer,nullable=False,server_default="0"); route=Column(String(32),nullable=False,server_default="user"); origin_id=Column(String(255)); origin_message_id=Column(String(255)); temporal_workflow_id=Column(String(255),unique=True); status=Column(String(32),nullable=False,server_default="queued"); mode=Column(String(32),nullable=False,server_default="live"); correlation_id=Column(UUID(as_uuid=True),nullable=False); causation_id=Column(UUID(as_uuid=True)); attempt=Column(Integer,nullable=False,server_default="1"); queued_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now()); started_at=Column(DateTime(timezone=True)); completed_at=Column(DateTime(timezone=True)); deadline_at=Column(DateTime(timezone=True)); failure_code=Column(String(128)); failure_summary=Column(Text); budget_snapshot=Column(JSONB,nullable=False,server_default=text("'{}'::jsonb")); usage_summary=Column(JSONB,nullable=False,server_default=text("'{}'::jsonb")); output_summary=Column(Text); state_before_artifact_id=Column(UUID(as_uuid=True),ForeignKey("artifacts.id",name="fk_agent_runs_state_before_artifact_id_artifacts",ondelete="SET NULL",use_alter=True)); state_after_artifact_id=Column(UUID(as_uuid=True),ForeignKey("artifacts.id",name="fk_agent_runs_state_after_artifact_id_artifacts",ondelete="SET NULL",use_alter=True)); state_diff_artifact_id=Column(UUID(as_uuid=True),ForeignKey("artifacts.id",name="fk_agent_runs_state_diff_artifact_id_artifacts",ondelete="SET NULL",use_alter=True)); resolution_status=Column(String(32)); resolved_at=Column(DateTime(timezone=True)); next_event_sequence=Column(Integer,nullable=False,server_default="1")

class AgentRunStep(Base):
    __tablename__="agent_run_steps"; __table_args__=(UniqueConstraint("run_id","ordinal"),)
    id=_id(); run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="CASCADE"),nullable=False); ordinal=Column(Integer,nullable=False); step_type=Column(String(32),nullable=False); status=Column(String(32),nullable=False); tool_identity=Column(String(512)); request_hash=Column(String(64)); risk=Column(String(32)); retries=Column(Integer,nullable=False,server_default="0"); summary=Column(Text); error=Column(Text); created_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now()); completed_at=Column(DateTime(timezone=True))

class AgentAction(Base):
    __tablename__="agent_actions"; __table_args__=(UniqueConstraint("run_id","action_id"),UniqueConstraint("run_id","idempotency_key"), CheckConstraint("status IN ('planned','policy_denied','awaiting_approval','authorized','denied','expired','cancelled','executing','simulated','succeeded','failed','outcome_unknown','reconciled_succeeded','reconciled_failed','operator_closed')"))
    id=_id(); run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="CASCADE"),nullable=False); step_id=Column(UUID(as_uuid=True),ForeignKey("agent_run_steps.id",ondelete="SET NULL")); action_id=Column(String(128),nullable=False); idempotency_key=Column(String(255),nullable=False); revision=Column(Integer,nullable=False,server_default="1"); tool_identity=Column(String(512),nullable=False); arguments=Column(JSONB,nullable=False); target=Column(JSONB,nullable=False,server_default=text("'{}'::jsonb")); request_hash=Column(String(64),nullable=False); status=Column(String(32),nullable=False,server_default="planned"); simulated=Column(Boolean,nullable=False,server_default="false"); authorization_ref=Column(String(255)); authorization_hash=Column(String(64)); policy_decision=Column(JSONB); provider_receipt=Column(JSONB); created_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now()); updated_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now()); outcome_unknown_at=Column(DateTime(timezone=True))

class AgentRunEvent(Base):
    __tablename__="agent_run_events"; __table_args__=(UniqueConstraint("run_id","sequence"),Index("idx_agent_run_events_run_sequence","run_id","sequence"))
    id=_id(); run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="CASCADE"),nullable=False); sequence=Column(Integer,nullable=False); schema_version=Column(Integer,nullable=False,server_default="1"); event_type=Column(String(128),nullable=False); payload=Column(JSONB,nullable=False,server_default=text("'{}'::jsonb")); created_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now())

class AgentStateSnapshot(Base):
    __tablename__="agent_state_snapshots"; __table_args__=(Index("idx_agent_state_snapshots_agent_created","agent_id","created_at"),)
    id=_id(); workspace_id=Column(UUID(as_uuid=True),ForeignKey("workspaces.id",ondelete="CASCADE"),nullable=False); agent_id=Column(UUID(as_uuid=True),ForeignKey("agents.id",ondelete="CASCADE"),nullable=False); run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="SET NULL")); state_hash=Column(String(64),nullable=False); state=Column(JSONB,nullable=False); created_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now())

class Artifact(Base):
    __tablename__="artifacts"
    id=_id(); workspace_id=Column(UUID(as_uuid=True),ForeignKey("workspaces.id",ondelete="CASCADE"),nullable=False); run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="SET NULL")); content_type=Column(String(255),nullable=False); size_bytes=Column(Integer,nullable=False); sha256=Column(String(64),nullable=False); classification=Column(String(32),nullable=False); storage_backend=Column(String(32),nullable=False); storage_key=Column(String(1024),nullable=False); retention_until=Column(DateTime(timezone=True)); legal_hold=Column(Integer,nullable=False,server_default="0"); created_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now())

class ThreadExecutionLease(Base):
    __tablename__="thread_execution_leases"; __table_args__=(UniqueConstraint("thread_id"),)
    id=_id(); workspace_id=Column(UUID(as_uuid=True),ForeignKey("workspaces.id",ondelete="CASCADE"),nullable=False); thread_id=Column(UUID(as_uuid=True),ForeignKey("threads.id",ondelete="CASCADE"),nullable=False); run_id=Column(UUID(as_uuid=True),ForeignKey("agent_runs.id",ondelete="CASCADE")); execution_type=Column(String(32),nullable=False,server_default="agent_run"); execution_id=Column(String(255)); holder=Column(String(255),nullable=False); expires_at=Column(DateTime(timezone=True),nullable=False); created_at=Column(DateTime(timezone=True),nullable=False,server_default=func.now())
