"""Phase 3 typed handoffs, SLA escalation, reservations, retention and advice."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "0012_phase3"; down_revision = "0011_credential_fk_approval"; branch_labels = None; depends_on = None
def upgrade():
    op.create_table("handoff_contracts", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("version", sa.Integer, nullable=False), sa.Column("source_capability", sa.String(255), nullable=False), sa.Column("target_capability", sa.String(255), nullable=False), sa.Column("input_schema", postgresql.JSONB, nullable=False), sa.Column("output_schema", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("target_allowlist", postgresql.JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("artifact_classifications", postgresql.JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("timeout_seconds", sa.Integer, nullable=False, server_default="300"), sa.Column("max_depth", sa.Integer, nullable=False, server_default="3"), sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("workspace_id", "name", "version"))
    op.create_table("agent_handoffs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("contract_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("source_run_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("target_agent_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("input_payload", postgresql.JSONB, nullable=False), sa.Column("output_payload", postgresql.JSONB), sa.Column("origin_chain", postgresql.JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("hop_count", sa.Integer, nullable=False, server_default="0"), sa.Column("idempotency_key", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="pending"), sa.Column("response_mode", sa.String(16), nullable=False, server_default="async"), sa.Column("acknowledgement_deadline", sa.DateTime(timezone=True)), sa.Column("completion_deadline", sa.DateTime(timezone=True)), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.ForeignKeyConstraint(["workspace_id"],["workspaces.id"],ondelete="CASCADE"), sa.ForeignKeyConstraint(["contract_id"],["handoff_contracts.id"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["source_run_id"],["agent_runs.id"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["target_agent_id"],["agents.id"],ondelete="RESTRICT"), sa.UniqueConstraint("workspace_id", "idempotency_key"))
    op.create_table("handoff_escalations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("handoff_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("stage", sa.String(64), nullable=False), sa.Column("target_type", sa.String(32), nullable=False), sa.Column("target_id", sa.String(255), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="pending"), sa.Column("fired_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.ForeignKeyConstraint(["workspace_id"],["workspaces.id"],ondelete="CASCADE"), sa.ForeignKeyConstraint(["handoff_id"],["agent_handoffs.id"],ondelete="CASCADE"), sa.UniqueConstraint("handoff_id","stage"))
    op.create_table("policy_recommendations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("evidence", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("proposed_diff", postgresql.JSONB, nullable=False), sa.Column("risk", sa.String(32), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="pending"), sa.Column("accepted_draft_id", postgresql.UUID(as_uuid=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True)))
    op.create_table("artifact_tombstones", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("artifact_id", postgresql.UUID(as_uuid=True), nullable=False, unique=True), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("reason", sa.String(255), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.ForeignKeyConstraint(["workspace_id"],["workspaces.id"],ondelete="CASCADE"))
def downgrade(): raise RuntimeError("Autonomy migrations are forward-only")
